require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Spree::ActiveSale::EventsController do

  # This should return the minimal set of attributes required to create a valid
  # Spree::ActiveSale::Event. As you add validations to Spree::ActiveSale::Event, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Spree::ActiveSale::EventsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all spree_active_sale_events as @spree_active_sale_events" do
      event = Spree::ActiveSale::Event.create! valid_attributes
      get :index, {}, valid_session
      assigns(:spree_active_sale_events).should eq([event])
    end
  end

  describe "GET show" do
    it "assigns the requested spree_active_sale as @spree_active_sale" do
      event = Spree::ActiveSale::Event.create! valid_attributes
      get :show, {:id => event.to_param}, valid_session
      assigns(:spree_active_sale).should eq(event)
    end
  end

  describe "GET new" do
    it "assigns a new spree_active_sale as @spree_active_sale" do
      get :new, {}, valid_session
      assigns(:spree_active_sale).should be_a_new(Spree::ActiveSale::Event)
    end
  end

  describe "GET edit" do
    it "assigns the requested spree_active_sale as @spree_active_sale" do
      event = Spree::ActiveSale::Event.create! valid_attributes
      get :edit, {:id => event.to_param}, valid_session
      assigns(:spree_active_sale).should eq(event)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Spree::ActiveSale::Event" do
        expect {
          post :create, {:spree_active_sale => valid_attributes}, valid_session
        }.to change(Spree::ActiveSale::Event, :count).by(1)
      end

      it "assigns a newly created spree_active_sale as @spree_active_sale" do
        post :create, {:spree_active_sale => valid_attributes}, valid_session
        assigns(:spree_active_sale).should be_a(Spree::ActiveSale::Event)
        assigns(:spree_active_sale).should be_persisted
      end

      it "redirects to the created spree_active_sale" do
        post :create, {:spree_active_sale => valid_attributes}, valid_session
        response.should redirect_to(Spree::ActiveSale::Event.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved spree_active_sale as @spree_active_sale" do
        # Trigger the behavior that occurs when invalid params are submitted
        Spree::ActiveSale::Event.any_instance.stub(:save).and_return(false)
        post :create, {:spree_active_sale => {  }}, valid_session
        assigns(:spree_active_sale).should be_a_new(Spree::ActiveSale::Event)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Spree::ActiveSale::Event.any_instance.stub(:save).and_return(false)
        post :create, {:spree_active_sale => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested spree_active_sale" do
        event = Spree::ActiveSale::Event.create! valid_attributes
        # Assuming there are no other spree_active_sale_events in the database, this
        # specifies that the Spree::ActiveSale::Event created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Spree::ActiveSale::Event.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => event.to_param, :spree_active_sale => { "these" => "params" }}, valid_session
      end

      it "assigns the requested spree_active_sale as @spree_active_sale" do
        event = Spree::ActiveSale::Event.create! valid_attributes
        put :update, {:id => event.to_param, :spree_active_sale => valid_attributes}, valid_session
        assigns(:spree_active_sale).should eq(event)
      end

      it "redirects to the spree_active_sale" do
        event = Spree::ActiveSale::Event.create! valid_attributes
        put :update, {:id => event.to_param, :spree_active_sale => valid_attributes}, valid_session
        response.should redirect_to(event)
      end
    end

    describe "with invalid params" do
      it "assigns the spree_active_sale as @spree_active_sale" do
        event = Spree::ActiveSale::Event.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Spree::ActiveSale::Event.any_instance.stub(:save).and_return(false)
        put :update, {:id => event.to_param, :spree_active_sale => {  }}, valid_session
        assigns(:spree_active_sale).should eq(event)
      end

      it "re-renders the 'edit' template" do
        event = Spree::ActiveSale::Event.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Spree::ActiveSale::Event.any_instance.stub(:save).and_return(false)
        put :update, {:id => event.to_param, :spree_active_sale => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested spree_active_sale" do
      event = Spree::ActiveSale::Event.create! valid_attributes
      expect {
        delete :destroy, {:id => event.to_param}, valid_session
      }.to change(Spree::ActiveSale::Event, :count).by(-1)
    end

    it "redirects to the spree_active_sale_events list" do
      event = Spree::ActiveSale::Event.create! valid_attributes
      delete :destroy, {:id => event.to_param}, valid_session
      response.should redirect_to(spree_active_sale_events_url)
    end
  end

end
